# Generated by Django 4.2.1 on 2023-06-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add',
            new_name='addCart',
        ),
    ]
